--- 
    
  - hosts: openldap_servers:children
    roles:
      - common
          
  - hosts: openldap_masters
    roles:
      - openldap_masters
      
  - hosts: openldap_clients
    roles:
      - openldap_clients