---

- name: Add RPM key for logstash repo
  rpm_key: state=present key=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: Add yum repo conf for Logstash
  template: src=logstash_repo.j2 dest={{ repo_conf_path }}/logstash.repo

- name: Install Logstash from local repo
  yum: name={{ item }} state=present
  with_items:
    - logstash

- name: Copy Logstash's avid conf
  template: src=aether_conf.j2 dest={{ logstash_conf_dir }}/aether.conf owner=root group=root mode=0644

- name: Restart Logstash
  service: name=logstash state=restarted